In [9]:
from sentence_transformers import SentenceTransformer
from sentence_transformers import util

### Embeddings Model:

In [3]:
model= SentenceTransformer("all-MiniLM-L6-v2")

e:\JMM\JMMProjects\SMLT\myenv\lib\site-packages\huggingface_hub\file_download.py:149: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\DELL\.cache\huggingface\hub\models--sentence-transformers--all-MiniLM-L6-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


In [4]:
sentences= ['Computer is a useful machine.',
            'Laptop uses battery for usage without electriciyt.',
            'The dog is faithful animal']

In [5]:
embeddings= model.encode(sentences,
                         #we want to get tensors
                        convert_to_tensor= True)

embeddings

tensor([[-0.0068,  0.0463,  0.0471,  ...,  0.0602,  0.0242, -0.0619],
        [-0.0221,  0.0827, -0.0365,  ..., -0.0146,  0.0455, -0.0206],
        [-0.0420, -0.0552,  0.0284,  ...,  0.0622,  0.0737,  0.0208]])

In [6]:
embeddings.shape

torch.Size([3, 384])

**Comparing sentences that are related (first and second)**

In [11]:
cosine_scores1_2= util.cos_sim(embeddings[0],
                            embeddings[1])

cosine_scores1_2

tensor([[0.4007]])

**Now lets compare sentences that are not related**

In [12]:
cosine_scores1_3= util.cos_sim(embeddings[0],
                            embeddings[2])

cosine_scores1_3

tensor([[-0.0561]])